// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyTeams.Frontend.ServicePoC.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ChannelDto
    {
        /// <summary>
        /// Initializes a new instance of the ChannelDto class.
        /// </summary>
        public ChannelDto() { }

        /// <summary>
        /// Initializes a new instance of the ChannelDto class.
        /// </summary>
        public ChannelDto(int? id = default(int?), string displayName = default(string), int? teamId = default(int?))
        {
            Id = id;
            DisplayName = displayName;
            TeamId = teamId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "teamId")]
        public int? TeamId { get; set; }

    }
}
