// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyTeams.Frontend.ServicePoC.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MessageDto
    {
        /// <summary>
        /// Initializes a new instance of the MessageDto class.
        /// </summary>
        public MessageDto() { }

        /// <summary>
        /// Initializes a new instance of the MessageDto class.
        /// </summary>
        public MessageDto(int? id = default(int?), int? channelId = default(int?), int? fromId = default(int?), string text = default(string), string imageUrl = default(string), DateTime? sent = default(DateTime?), bool? isImageMessage = default(bool?))
        {
            Id = id;
            ChannelId = channelId;
            FromId = fromId;
            Text = text;
            ImageUrl = imageUrl;
            Sent = sent;
            IsImageMessage = isImageMessage;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channelId")]
        public int? ChannelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromId")]
        public int? FromId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imageUrl")]
        public string ImageUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sent")]
        public DateTime? Sent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isImageMessage")]
        public bool? IsImageMessage { get; set; }

    }
}
