// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyTeams.Frontend.ServicePoC.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class User
    {
        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User() { }

        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User(string firstname, string lastname, string fullname = default(string), string avatarUrl = default(string), int? id = default(int?), byte[] rowVersion = default(byte[]))
        {
            Firstname = firstname;
            Lastname = lastname;
            Fullname = fullname;
            AvatarUrl = avatarUrl;
            Id = id;
            RowVersion = rowVersion;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstname")]
        public string Firstname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastname")]
        public string Lastname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fullname")]
        public string Fullname { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "avatarUrl")]
        public string AvatarUrl { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rowVersion")]
        public byte[] RowVersion { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Firstname == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Firstname");
            }
            if (Lastname == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Lastname");
            }
        }
    }
}
